services:
  - name: example-service
    repository: microservices
    location: us-central1
    package: example-service
    jenkins_job: image-rebuild/example-service
    tag_prefix: v
    base_image: python:3.12-slim
    git_repo_url: https://github.com/Sumanth12-afk/Jenkins_job.git
    git_branch: main
    dockerfile_path: sample_services/example-service/Dockerfile
    build_context: sample_services/example-service
